### ISSUE TITLE
relative timelines 

### ISSUE THREAD

**Issue by eMPee584** [linuxhw/Trends#1]
Salut, in many cases (f.e. https://linux-hardware.org/index.php?view=os_boot_mode) it would be more useful to show a relative timeline graph to indicate the change in proportion. Of course, absolute figures are interesting on some factoids too. 😄

**Comment by linuxhw** [comment]
Hello,

Do you know good examples of such charts?

Thanks.

**Comment by bsdhw** [comment]
Implemented.

Thanks for the idea!

Select `scale = mon_rel` or `scale = year_rel`.

Available scales:

| Scale   | Meaning |
|----------|---------|
| month    | Sum per month |
| year    | Sum per year |
| mon_12 | Sum per month with 12-month interval |
| mon_rel   | Sum per month (relative to leader, in percents) |
| year_rel  | Sum per year (relative to leader, in percents) |

See https://linux-hardware.org/?view=node_vendor

![RelTimeline](https://user-images.githubusercontent.com/64436175/84933987-5e080180-b0df-11ea-8341-aabe3e080453.png)
